"""soccer_players

Revision ID: 91fc907abbf5
Revises: 9faa1dca8a50
Create Date: 2024-04-15 15:17:46.504478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fc907abbf5'
down_revision = '9faa1dca8a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soccer_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=True),
    sa.Column('extra', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soccer_player')
    # ### end Alembic commands ###
