"""stocks

Revision ID: bb7ba71d6300
Revises: 91fc907abbf5
Create Date: 2024-04-21 09:19:15.623575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7ba71d6300'
down_revision = '91fc907abbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=True),
    sa.Column('extra', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    # ### end Alembic commands ###
